apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: maptheisland-local-vault
  labels:
    maptheisland.io/scope: local-only
spec:
  provider:
    vault:
      server: http://maptheisland-vault.maptheisland-dev-foundation-system.svc.cluster.local:8200
      path: secret
      version: v2
      auth:
        tokenSecretRef:
          name: maptheisland-local-vault-token
          key: token
          namespace: maptheisland-dev-foundation-system
