apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: maptheisland-local-sample-secret
  namespace: maptheisland-dev-application
  labels:
    app.kubernetes.io/name: maptheisland-local-sample-consumer
    maptheisland.io/scope: local-only
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: maptheisland-local-vault
  target:
    name: maptheisland-local-sample-runtime
    creationPolicy: Owner
    template:
      metadata:
        labels:
          app.kubernetes.io/name: maptheisland-local-sample-consumer
      type: Opaque
  data:
    - secretKey: API_TOKEN
      remoteRef:
        key: maptheisland/local/sample-service
        property: api_token
