apiVersion: v1
kind: ServiceAccount
metadata:
  name: maptheisland-local-sample-consumer
  namespace: maptheisland-dev-application
  labels:
    app.kubernetes.io/name: maptheisland-local-sample-consumer
    maptheisland.io/scope: local-only
